# Используем официальный Python 3.10 slim
FROM python:3.10-slim

# Рабочая папка в контейнере
WORKDIR /app

# Копируем зависимости
COPY requirements-sheets.txt requirements.txt

# Устанавливаем Python-библиотеки
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект внутрь контейнера
COPY . .

# Открываем порт для Flask
EXPOSE 5001

# Запуск Flask
CMD ["python", "data_sheets.py"]
